language: python
python:
- "2.7"
services:
- mongodb
install: "pip install -r requirements.txt"
script: coverage run --source plantmeter ./setup.py test
install:
- pip install coveralls
after_success:
- coveralls

