language: python
python:
- "2.7"
- "3.4"
- "3.7"
services:
- mongodb
install:
- pip install -r requirements.txt
- pip install coveralls
script: coverage run --source plantmeter ./setup.py test
after_success:
- coveralls

